# Generated by Django 4.2.3 on 2023-07-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_sub_category_name_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_category_name',
            new_name='parent_category',
        ),
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category'),
        ),
    ]
