# Generated by Django 4.2.3 on 2023-07-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_sub_category_name_category_parent_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subcategory',
            new_name='parent_category',
        ),
    ]
