# Generated by Django 4.2.3 on 2023-07-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_category_post_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sub_category',
            new_name='category',
        ),
    ]
