# Generated by Django 4.2.3 on 2023-07-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_comment_author2_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
