# Generated by Django 4.2.3 on 2023-07-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_cevap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cevap',
            old_name='metin',
            new_name='text',
        ),
    ]
