# Generated by Django 4.2.3 on 2023-07-24 08:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_comment_level_comment_lft_comment_rght_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
