# Generated by Django 4.2.3 on 2023-07-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_alter_post_up_and_down'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='up_and_down',
        ),
    ]
