# Generated by Django 4.2.3 on 2023-07-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_remove_post_up_and_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='up',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
