# Generated by Django 4.2.3 on 2023-07-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_post_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='voters',
            new_name='has_voted',
        ),
    ]
