# Generated by Django 4.2.3 on 2023-07-26 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0050_rename_voters_post_has_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='has_voted',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_posts', through='blog.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
