# Generated by Django 4.2.3 on 2023-07-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_remove_post_has_voted_vote_post_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='up',
        ),
        migrations.RemoveField(
            model_name='post',
            name='voters',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
